{
 "title": "FWTester",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Network test results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(status) (count_over_time({app=\"FWTester\", status=~\"KO|OK\"} [1h]))"
    }
   ]
  },
  {
   "title": "Complete log",
   "type": "logs",
   "gridPos": { "h": 23, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"FWTester\", status=~\"KO|OK\"} |= ``"
    }
   ]
  },
  {
   "title": "Last KO",
   "type": "table",
   "gridPos": { "h": 15, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "{app=\"FWTester\", status=\"KO\"}"
    }
   ]
  }
 ]
}