{
 "title": "Monitoring macro Flux/ESB",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": " <img src=\"https://upload.wikimedia.org/wikipedia/commons/5/5b/Korian_logo_2020.svg\">"
   }
  },
  {
   "title": "Pentaho EAI Interfaces, dernières 24 heures",
   "type": "table",
   "description": "Dernier status connu de chaque interfaces sur 24 heures glissantes",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"PentahoEAI_vs_vtom_daily\"}"
    }
   ]
  },
  {
   "title": "Blueway Services, dernières 24 heures",
   "type": "table",
   "description": "Etat des service blueway sur 24h",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"Blueway_services_monitoring\"}"
    }
   ]
  },
  {
   "title": "Informations utile",
   "type": "text",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 5 },
   "options": {
    "content": "* bonne année 🎉\r\n* merci de remplir vos cras✔️"
   }
  },
  {
   "title": "Applications innactives dans VTOM",
   "type": "table",
   "description": "Base sur les ressources RP_FLOW_xxx et RP_BI_xxx ayant une valeur maximum a 0",
   "gridPos": { "h": 9, "w": 4, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{app=\"VTom_ressources\"}"
    }
   ]
  },
  {
   "title": "Endpoints HTTP GET status",
   "type": "table",
   "description": "GET http ou https fait sur des endpoint depuis le kor0223vm-pen. ok si statut 200",
   "gridPos": { "h": 9, "w": 4, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"Endpoints_status\"}"
    }
   ]
  },
  { "title": "Services blueway OFF", "type": "text", "gridPos": { "h": 9, "w": 13, "x": 11, "y": 8 }, "options": { "content": "Coming soon 🚧" } }
 ]
}