{
 "title": "Suivi volume Loki",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Messages",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (loki_log_messages_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingested data",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (loki_ingester_chunk_stored_bytes_total{tenant=\"docker\"})"
    }
   ]
  },
  {
   "title": "Utilisation (Nb querries)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(loki_ingester_client_request_duration_seconds_count{operation=\"/logproto.Querier/Query\", status_code=\"2xx\"}[$__rate_interval])"
    }
   ]
  }
 ]
}