{
 "title": "Suivi LOG Blueway",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Logs Blueway PROD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({app=\"Blueway\",env=\"PROD\",level!=\"\"}[10m])) by (level)"
    }
   ]
  },
  {
   "title": "Logs Blueway DEV",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({app=\"Blueway\",env=\"DEV\",level!=\"\"}[10m])) by (level)"
    }
   ]
  },
  {
   "title": "Logs Blueway REC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({app=\"Blueway\",env=\"REC\",level!=\"\"}[10m])) by (level)"
    }
   ]
  },
  {
   "title": "Logs Blueway UPG",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({app=\"Blueway\",env=\"UPG\",level!=\"\"}[10m])) by (level)"
    }
   ]
  },
  {
   "title": "Logs Blueway PPD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({app=\"Blueway\",env=\"PPD\",level!=\"\"}[10m])) by (level)"
    }
   ]
  }
 ]
}