{
 "title": "Suivi LOG Pentaho EAI",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Logs Pentaho EAI PROD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({app=\"Pentaho_EAI\",env=\"PROD\",level!=\"\"}[10m])) by (level)"
    }
   ]
  },
  {
   "title": "Logs Pentaho EAI REC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({app=\"Pentaho_EAI\",env=\"REC\",level!=\"\"}[10m])) by (level)"
    }
   ]
  },
  {
   "title": "Logs Pentaho EAI INT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({app=\"Pentaho_EAI\",env=\"INT\",level!=\"\"}[10m])) by (level)"
    }
   ]
  }
 ]
}