apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: grafana
  storageClassName: hostpath