server:
  http_listen_port: 9080
  grpc_listen_port: 0
 
positions:
  filename: ./positions.yaml
 
clients:
  - url: https://loki-flux-prod.korian.cloud/loki/api/v1/push
    tenant_id: docker
    
scrape_configs:
- job_name: Blueway_dev
  static_configs:
  - labels:
      app: Blueway
      env: DEV
      server: kor2561vm-bwy-d
      __path__: e:\blueway\BluewayEngine\logs\blueway-engine.log
  pipeline_stages:
  - match:
      selector: '{app="Blueway"}'
      stages:
      - regex:
          expression: '(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) (?P<level>[^ ]*)'
      - multiline:
          firstline: '(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})'
          max_wait_time: 3s 
          max_lines: 128
      - labels:
          level:
      - timestamp:
          source: time 
          format: 2006-01-02 15:04:05,000
          location: Europe/Paris
          action_on_failure: fudge
- job_name: FWTester
  static_configs:
  - labels:
      app: FWTester
      __path__: E:\FWTester\log\result\*.log
  pipeline_stages:
    - match:
        selector: '{app="FWTester"}'
        stages:
        - json:
            expressions:
              status: status
        - labels:
            status: