server:
  http_listen_port: 9080
  grpc_listen_port: 0
 
positions:
  filename: ./positions.yaml
 
clients:
  - url: https://loki.apps.prod.korian.cloud/loki/api/v1/push
    basic_auth:
      username: user
      password: pass

scrape_configs:
- job_name: SCLite_rec
  static_configs:
  - labels:
      app: SClite
      logger: SClite
      env: REC
      server: kor2312vm-scl-r
      __path__: E:\sfwy\REC2\*\*.log
  pipeline_stages:
  - match:
      selector: '{app="SClite"}'
      stages:
      - regex:
          expression: '^(\d{2}:\d{2}:\d{2})'
      - multiline:
          firstline: '^(\d{2}:\d{2}:\d{2})'
          max_wait_time: 3s 
          max_lines: 150
- job_name: Pentaho_EAI_WinEvents 
  windows_events:
    use_incoming_timestamp: false
    bookmark_path: "./bookmark.xml"
    eventlog_name: "System"
    xpath_query: '*[System[EventID=7036]]'
    labels:
      job: Pentaho_EAI_WinEvents
      env: INT
      server: kor2352vm-EAI-I
      app: Pentaho_EAI_WinEvents
  relabel_configs:
    - source_labels: ['computer']
      target_label: 'host'