server:
  http_listen_port: 9080
  grpc_listen_port: 0
 
positions:
  filename: ./positions.yaml
 
clients:
  - url: https://loki.apps.prod.korian.cloud/loki/api/v1/push
    basic_auth:
      username: user
      password: pass
    # tls_config:
    #   insecure_skip_verify: true
scrape_configs:
- job_name: Pentaho_EAI
  static_configs:
  - labels:
      app: Pentaho_EAI
      logger: pentaho
      env: INT
      server: kor2352vm-EAI-I
      __path__: E:\pentaho\server\pentaho-server\tomcat\logs\pentaho.log
  pipeline_stages:
  - match:
      selector: '{app="Pentaho_EAI"}'
      stages:
      - regex:
          expression: '(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})[ ]+(?P<level>[^ ]*)[ ]+(?P<class>\[.*\])'
      - multiline:
          firstline: '(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}[ ]+[^ ]*[ ]+\[.*\])'
          max_wait_time: 3s 
          max_lines: 150
      - labels:
          level:
          class:
      - drop:
          source: level
          expression: "(INFO|DEBUG|^$)"           
      - timestamp:
          source: time 
          format: 2006-01-02 15:04:05,000
          location: Europe/Paris
          action_on_failure: fudge
- job_name: Pentaho_EAI_ERR
  static_configs:
  - labels:
      app: Pentaho_EAI
      logger: tomcat8-stderr
      env: INT
      server: kor2352vm-EAI-I
      __path__: E:\pentaho\server\pentaho-server\tomcat\logs\tomcat8-stderr.log
  pipeline_stages:
  - match:
      selector: '{app="Pentaho_EAI"}'
      stages:
      - drop:
          expression: "(        at).*"
- job_name: Pentaho_EAI_WinEvents 
  windows_events:
    use_incoming_timestamp: false
    bookmark_path: "./bookmark.xml"
    eventlog_name: "System"
    xpath_query: '*[System[EventID=7036]]'
    labels:
      job: Pentaho_EAI_WinEvents
      env: INT
      server: kor2352vm-EAI-I
      app: Pentaho_EAI_WinEvents
  relabel_configs:
    - source_labels: ['computer']
      target_label: 'host'